on: workflow_dispatch
permissions:
  contents: write
  pull-requests: write
name: release-please-stable

jobs:
  release-please-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: flowplayer/playback-github-actions/release-please@main
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          config-file: config/release-please-stable-config.json
          manifest-file: config/.release-please-stable-manifest.json
          component-name-in-branch: "translations"
